# Generated by Django 5.2.13 on 2026-04-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('individual_chit_amount', models.DecimalField(decimal_places=2, help_text='Amount per single chit unit per month', max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_chits', models.PositiveIntegerField(default=1)),
                ('total_chit_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: number_of_chits × individual_chit_amount', max_digits=12)),
                ('chitgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='chitgroups.chitgroup')),
            ],
            options={
                'ordering': ['chitgroup', 'user'],
            },
        ),
    ]
