version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=0

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://tharavadukuris.oopsops.in/api
    # Standalone build doesn't need volumes for code

  nginx:
    build: ./nginx
    ports:
      - 5698:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend/media:/app/media # Link media to host
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
