# Generated by Django 5.2.13 on 2026-04-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chitgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('screenshot_url', models.CharField(blank=True, default='', help_text='Relative path to the uploaded screenshot', max_length=500)),
                ('payment_month', models.DateField(help_text='First day of the payment month (YYYY-MM-01)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyChitWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_won', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chitgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='chitgroups.chitgroup')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
