# Generated by Django 5.2.13 on 2026-04-21 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chitgroups', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlychitwinner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chit_wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='chitgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='chitgroups.chitgroup'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthlychitwinner',
            unique_together={('chitgroup', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'chitgroup', 'payment_month')},
        ),
    ]
