# Generated by Django 5.2.13 on 2026-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlychitwinner',
            name='payment_confirmation_url',
            field=models.CharField(blank=True, default='', help_text='Relative path to the uploaded payment confirmation screenshot', max_length=500),
        ),
    ]
